### ISSUE TITLE
Plan to add support for TP-LINK TL-WR740N V5?

### ISSUE THREAD

**Issue by ikky888** [LeeXiaolan/tplink-vxworks-based-firmware#2]
As in title

**Comment by LeeXiaolan** [comment]
Sorry, no such plan in the near future.

**Comment by ikky888** [comment]
I can help you work on adding support but I need to understand a few parts of the code.

1) For example here:
MODELS = {
  'WVR300V1': {
    'id': '\x03\x00\x00\x01\x00\x00\x00\x01',
    'md5Placeholder': DEFAULT_MD5_PLACEHOLDER,
  },
  'R478V3': {
    'id': '\x04\x78\x00\x05\x00\x00\x00\x01',
    'md5Placeholder': '\x56\x2e\x0a\xc5\xf7\x81\xda\xcf\x12\xd7\xb2\x56\x35\x0f\xba\x8d',
  },

Shouldn't the ID fo R478v3 be instead '\x04\x78\x00\x03\x00\x00\x00\x01'?

**Comment by LeeXiaolan** [comment]
> Shouldn't the ID fo R478v3 be instead '\x04\x78\x00\x03\x00\x00\x00\x01'?

Normally that is true. But sometimes vendor lies, like this [R478 V3 120610](http://service.tp-link.com.cn/detail_download_839.html), or maybe just compatible, who knows.
